from pathlib import Path
p=Path('outputs/hcmc-poc/index.html'); s=p.read_text()
s=s.replace('POC 11 / CONFIDENCE + ACQUISITION PRIORITY','POC 12 / CINEMATIC NIGHT + MAP-FIRST UI')
s=s.replace('mười bảy góc nhìn','mười tám góc nhìn')
s=s.replace('11: độ tin cậy &amp; ưu tiên thu thập ↗</a>','11: độ tin cậy &amp; ưu tiên thu thập ↗</a> · <a href="../POC-12-CINEMATIC-MAP-UI.md" target="_blank">12: cinematic night &amp; map-first UI ↗</a>')
s=s.replace('PoC 11 chấm điểm độ tin cậy cho 70.719 công trình, tổng hợp thành lưới 8 × 8 và xếp 12 ô ưu tiên thu thập. Điểm chỉ dùng để lập kế hoạch; ảnh mới và reality tile khảo sát vẫn bằng 0, chưa xét phép bay, không phận, thời tiết hoặc tiếp cận hiện trường.','PoC 12 bổ sung blue hour, bloom nhiều tầng, color grading, vệt đèn, mặt đường ẩm và Camera Director 45 giây. Giao diện chuyển sang map-first: giới thiệu, góc nhìn, trình diễn và các HUD đều có thể thu gọn để trả không gian cho bản đồ.')
s=s.replace('<script src="confidence-map-11.js?v=11c"></script>','<script src="confidence-map-11.js?v=12a"></script><script src="cinematic-night-12.js?v=12a"></script>')
s=s.replace('?v=11c','?v=12a')
p.write_text(s)

p=Path('outputs/hcmc-poc/app.js'); s=p.read_text()
s=s.replace('if(window.advanceConfidenceMap)window.advanceConfidenceMap(dt,now);','if(window.advanceConfidenceMap)window.advanceConfidenceMap(dt,now);if(window.advanceCinematic12)window.advanceCinematic12(dt,now);')
s=s.replace('if(window.renderRiverReflection)window.renderRiverReflection();renderer.render(scene,camera);','if(window.renderRiverReflection)window.renderRiverReflection();if(!(window.renderCinematic&&window.renderCinematic(now)))renderer.render(scene,camera);')
s=s.replace('confidenceMap:window.confidenceMapStatus};','confidenceMap:window.confidenceMapStatus,cinematic12:window.cinematic12Status};')
s=s.replace('PoC 11 · derived acquisition priority / 0 surveyed tiles','PoC 12 · cinematic blue hour / procedural presentation')
s=s.replace("const name='poc-eleven-'", "const name='poc-twelve-'")
p.write_text(s)

p=Path('outputs/hcmc-poc/reality-patch.js'); s=p.read_text(); s=s.replace("window.realityPatchStatus={enabled:rpGroup.visible", "rpHud.hidden=window.currentView!=='patchlab';window.realityPatchStatus={enabled:rpGroup.visible"); p.write_text(s)
p=Path('outputs/hcmc-poc/reality-tile-07b.js'); s=p.read_text(); old="rtHud.hidden=['groundcapture','bason','footbridge','materials','atlas','detail','confidence'].includes(window.currentView)||(window.currentView!=='realitytile'&&cameraDistance>1150)"; s=s.replace(old,"rtHud.hidden=window.currentView!=='realitytile'"); p.write_text(s)
p=Path('outputs/hcmc-poc/ground-capture-07c.js'); s=p.read_text(); old="gcHud.hidden=['bason','footbridge','materials','atlas','detail','confidence'].includes(window.currentView)||(window.currentView!=='groundcapture'&&!near)"; s=s.replace(old,"gcHud.hidden=window.currentView!=='groundcapture'"); p.write_text(s)
