from pathlib import Path
p=Path('outputs/hcmc-poc/index.html'); s=p.read_text()
s=s.replace('POC 10 / URBAN DETAIL + PERCEPTUAL REALISM','POC 11 / CONFIDENCE + ACQUISITION PRIORITY')
s=s.replace('mười sáu góc nhìn','mười bảy góc nhìn')
s=s.replace('10: chi tiết đô thị cảm nhận ↗</a>','10: chi tiết đô thị cảm nhận ↗</a> · <a href="../POC-11-CONFIDENCE-ACQUISITION.md" target="_blank">11: độ tin cậy &amp; ưu tiên thu thập ↗</a>')
s=s.replace('PoC 10 bổ sung 600 thiết bị mái, 240 dải hiệu không thương hiệu, 24 khối sương và chiều sâu khung cửa cho toàn cảnh. Mọi chi tiết mới đều là minh họa thủ tục gắn với footprint hiện có; chúng không khẳng định hiện trạng từng công trình.','PoC 11 chấm điểm độ tin cậy cho 70.719 công trình, tổng hợp thành lưới 8 × 8 và xếp 12 ô ưu tiên thu thập. Điểm chỉ dùng để lập kế hoạch; ảnh mới và reality tile khảo sát vẫn bằng 0, chưa xét phép bay, không phận, thời tiết hoặc tiếp cận hiện trường.')
s=s.replace('<script src="data/urban-detail-10.js"></script>','<script src="data/urban-detail-10.js"></script><script src="data/confidence-map-11.js"></script>')
s=s.replace('<script src="urban-detail-10.js?v=10c"></script>','<script src="urban-detail-10.js?v=11a"></script><script src="confidence-map-11.js?v=11a"></script>')
s=s.replace('?v=10c','?v=11a')
p.write_text(s)
p=Path('outputs/hcmc-poc/app.js'); s=p.read_text()
s=s.replace('if(window.advanceUrbanDetail)window.advanceUrbanDetail(dt,now);','if(window.advanceUrbanDetail)window.advanceUrbanDetail(dt,now);if(window.advanceConfidenceMap)window.advanceConfidenceMap(dt,now);')
s=s.replace('urbanDetail:window.urbanDetailStatus};','urbanDetail:window.urbanDetailStatus,confidenceMap:window.confidenceMapStatus};')
s=s.replace('PoC 10 · procedural urban detail / not surveyed','PoC 11 · derived acquisition priority / 0 surveyed tiles')
s=s.replace("const name='poc-ten-'", "const name='poc-eleven-'")
p.write_text(s)
for name in ['ground-capture-07c.js','reality-tile-07b.js']:
 p=Path('outputs/hcmc-poc')/name; s=p.read_text(); s=s.replace("'atlas','detail'", "'atlas','detail','confidence'"); p.write_text(s)
